# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edge2d_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edge2d_window(object):
    def setupUi(self, edge2d_window):
        edge2d_window.setObjectName("edge2d_window")
        edge2d_window.resize(1049, 493)
        edge2d_window.setMinimumSize(QtCore.QSize(1049, 493))
        edge2d_window.setMaximumSize(QtCore.QSize(1049, 493))
        self.centralwidget = QtWidgets.QWidget(edge2d_window)
        self.centralwidget.setObjectName("centralwidget")
        self.edge2d_exit = QtWidgets.QPushButton(self.centralwidget)
        self.edge2d_exit.setGeometry(QtCore.QRect(580, 430, 101, 21))
        self.edge2d_exit.setObjectName("edge2d_exit")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(890, 10, 111, 211))
        self.groupBox.setObjectName("groupBox")
        self.rungetnames_button = QtWidgets.QPushButton(self.groupBox)
        self.rungetnames_button.setGeometry(QtCore.QRect(10, 160, 91, 25))
        self.rungetnames_button.setObjectName("rungetnames_button")
        self.frame_plot = QtWidgets.QFrame(self.groupBox)
        self.frame_plot.setGeometry(QtCore.QRect(10, 20, 91, 131))
        self.frame_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot.setLineWidth(5)
        self.frame_plot.setObjectName("frame_plot")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_plot)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_profile = QtWidgets.QCheckBox(self.frame_plot)
        self.checkBox_profile.setObjectName("checkBox_profile")
        self.verticalLayout_2.addWidget(self.checkBox_profile)
        self.checkBox_time = QtWidgets.QCheckBox(self.frame_plot)
        self.checkBox_time.setObjectName("checkBox_time")
        self.verticalLayout_2.addWidget(self.checkBox_time)
        self.checkBox_flux = QtWidgets.QCheckBox(self.frame_plot)
        self.checkBox_flux.setObjectName("checkBox_flux")
        self.verticalLayout_2.addWidget(self.checkBox_flux)
        self.checkBox_geom = QtWidgets.QCheckBox(self.frame_plot)
        self.checkBox_geom.setObjectName("checkBox_geom")
        self.verticalLayout_2.addWidget(self.checkBox_geom)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 130, 391, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.runcpmparesims_button = QtWidgets.QPushButton(self.groupBox_2)
        self.runcpmparesims_button.setGeometry(QtCore.QRect(20, 220, 112, 21))
        self.runcpmparesims_button.setObjectName("runcpmparesims_button")
        self.lineEdit_var = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_var.setGeometry(QtCore.QRect(10, 160, 361, 21))
        self.lineEdit_var.setObjectName("lineEdit_var")
        self.textEdit_message2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_message2.setGeometry(QtCore.QRect(0, 40, 381, 81))
        self.textEdit_message2.setObjectName("textEdit_message2")
        self.lineEdit_var_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_var_2.setGeometry(QtCore.QRect(260, 220, 101, 21))
        self.lineEdit_var_2.setObjectName("lineEdit_var_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 10, 441, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.runanalyze_button = QtWidgets.QPushButton(self.groupBox_3)
        self.runanalyze_button.setGeometry(QtCore.QRect(310, 10, 121, 21))
        self.runanalyze_button.setObjectName("runanalyze_button")
        self.lineEdit_1st = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1st.setGeometry(QtCore.QRect(10, 40, 171, 21))
        self.lineEdit_1st.setObjectName("lineEdit_1st")
        self.select_json1 = QtWidgets.QPushButton(self.groupBox_3)
        self.select_json1.setGeometry(QtCore.QRect(190, 40, 21, 21))
        self.select_json1.setObjectName("select_json1")
        self.lineEdit_2nd = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2nd.setGeometry(QtCore.QRect(10, 70, 171, 21))
        self.lineEdit_2nd.setObjectName("lineEdit_2nd")
        self.select_json2 = QtWidgets.QPushButton(self.groupBox_3)
        self.select_json2.setGeometry(QtCore.QRect(190, 70, 21, 21))
        self.select_json2.setObjectName("select_json2")
        self.enablecompare_check = QtWidgets.QCheckBox(self.groupBox_3)
        self.enablecompare_check.setGeometry(QtCore.QRect(220, 70, 121, 21))
        self.enablecompare_check.setObjectName("enablecompare_check")
        self.edit_JSON1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.edit_JSON1.setGeometry(QtCore.QRect(220, 40, 121, 21))
        self.edit_JSON1.setObjectName("edit_JSON1")
        self.edit_JSON2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.edit_JSON2.setGeometry(QtCore.QRect(340, 70, 91, 21))
        self.edit_JSON2.setObjectName("edit_JSON2")
        self.textEdit_message = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_message.setGeometry(QtCore.QRect(430, 140, 271, 241))
        self.textEdit_message.setObjectName("textEdit_message")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(710, 10, 181, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.add_sim = QtWidgets.QPushButton(self.groupBox_4)
        self.add_sim.setGeometry(QtCore.QRect(10, 170, 71, 25))
        self.add_sim.setObjectName("add_sim")
        self.comboBox_Name = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Name.setGeometry(QtCore.QRect(10, 20, 120, 25))
        self.comboBox_Name.setEditable(True)
        self.comboBox_Name.setObjectName("comboBox_Name")
        self.comboBox_Date = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Date.setGeometry(QtCore.QRect(10, 110, 120, 25))
        self.comboBox_Date.setEditable(True)
        self.comboBox_Date.setObjectName("comboBox_Date")
        self.comboBox_Seq = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Seq.setGeometry(QtCore.QRect(10, 140, 120, 25))
        self.comboBox_Seq.setEditable(True)
        self.comboBox_Seq.setObjectName("comboBox_Seq")
        self.comboBox_Machine = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Machine.setGeometry(QtCore.QRect(10, 50, 120, 25))
        self.comboBox_Machine.setEditable(True)
        self.comboBox_Machine.setObjectName("comboBox_Machine")
        self.comboBox_Shot = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Shot.setGeometry(QtCore.QRect(10, 80, 120, 25))
        self.comboBox_Shot.setEditable(True)
        self.comboBox_Shot.setObjectName("comboBox_Shot")
        self.lineEdit_var_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_var_3.setGeometry(QtCore.QRect(90, 170, 81, 21))
        self.lineEdit_var_3.setObjectName("lineEdit_var_3")
        self.pushButton_profiles = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_profiles.setGeometry(QtCore.QRect(890, 230, 111, 25))
        self.pushButton_profiles.setObjectName("pushButton_profiles")
        self.pushButton_powerbalance = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_powerbalance.setGeometry(QtCore.QRect(890, 320, 111, 25))
        self.pushButton_powerbalance.setObjectName("pushButton_powerbalance")
        self.pushButton_pumpcurrents = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pumpcurrents.setGeometry(QtCore.QRect(890, 260, 111, 25))
        self.pushButton_pumpcurrents.setObjectName("pushButton_pumpcurrents")
        self.pushButton_contour = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_contour.setGeometry(QtCore.QRect(890, 350, 111, 25))
        self.pushButton_contour.setObjectName("pushButton_contour")
        self.pushButton_print = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_print.setGeometry(QtCore.QRect(890, 290, 111, 25))
        self.pushButton_print.setObjectName("pushButton_print")
        self.pushButton_radiation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_radiation.setGeometry(QtCore.QRect(890, 380, 111, 25))
        self.pushButton_radiation.setObjectName("pushButton_radiation")
        self.lineEdit_var_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_var_4.setGeometry(QtCore.QRect(720, 250, 161, 21))
        self.lineEdit_var_4.setObjectName("lineEdit_var_4")
        self.lineEdit_var_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_var_5.setGeometry(QtCore.QRect(720, 280, 161, 21))
        self.lineEdit_var_5.setObjectName("lineEdit_var_5")
        self.groupBox_4.raise_()
        self.edge2d_exit.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.textEdit_message.raise_()
        self.pushButton_profiles.raise_()
        self.pushButton_powerbalance.raise_()
        self.pushButton_pumpcurrents.raise_()
        self.pushButton_contour.raise_()
        self.pushButton_print.raise_()
        self.pushButton_radiation.raise_()
        self.lineEdit_var_4.raise_()
        self.lineEdit_var_5.raise_()
        edge2d_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(edge2d_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1049, 20))
        self.menubar.setObjectName("menubar")
        edge2d_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(edge2d_window)
        self.statusbar.setObjectName("statusbar")
        edge2d_window.setStatusBar(self.statusbar)

        self.retranslateUi(edge2d_window)
        QtCore.QMetaObject.connectSlotsByName(edge2d_window)

    def retranslateUi(self, edge2d_window):
        _translate = QtCore.QCoreApplication.translate
        edge2d_window.setWindowTitle(_translate("edge2d_window", "edge2d tools"))
        self.edge2d_exit.setText(_translate("edge2d_window", "exit"))
        self.groupBox.setTitle(_translate("edge2d_window", "Get sim names"))
        self.rungetnames_button.setText(_translate("edge2d_window", "run"))
        self.checkBox_profile.setText(_translate("edge2d_window", "Profile"))
        self.checkBox_time.setText(_translate("edge2d_window", "Time"))
        self.checkBox_flux.setText(_translate("edge2d_window", "Flux"))
        self.checkBox_geom.setText(_translate("edge2d_window", "Geom"))
        self.groupBox_2.setTitle(_translate("edge2d_window", "compare sims"))
        self.runcpmparesims_button.setText(_translate("edge2d_window", "run"))
        self.lineEdit_var.setText(_translate("edge2d_window", "variable"))
        self.lineEdit_var_2.setText(_translate("edge2d_window", "location"))
        self.label.setText(_translate("edge2d_window", "input dictionary"))
        self.label_2.setText(_translate("edge2d_window", "var name"))
        self.groupBox_3.setTitle(_translate("edge2d_window", "Analyze"))
        self.runanalyze_button.setText(_translate("edge2d_window", "run"))
        self.select_json1.setText(_translate("edge2d_window", "..."))
        self.select_json2.setText(_translate("edge2d_window", "..."))
        self.enablecompare_check.setText(_translate("edge2d_window", "compare pulse"))
        self.edit_JSON1.setText(_translate("edge2d_window", "edit JSON1"))
        self.edit_JSON2.setText(_translate("edge2d_window", "edit JSON2"))
        self.textEdit_message.setHtml(_translate("edge2d_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_4.setTitle(_translate("edge2d_window", "search sim"))
        self.add_sim.setText(_translate("edge2d_window", "add"))
        self.lineEdit_var_3.setText(_translate("edge2d_window", "label"))
        self.pushButton_profiles.setText(_translate("edge2d_window", "profiles"))
        self.pushButton_powerbalance.setText(_translate("edge2d_window", "power balance"))
        self.pushButton_pumpcurrents.setText(_translate("edge2d_window", "pump currents"))
        self.pushButton_contour.setText(_translate("edge2d_window", "contour plot"))
        self.pushButton_print.setText(_translate("edge2d_window", "download print"))
        self.pushButton_radiation.setText(_translate("edge2d_window", "radiation contour"))
        self.lineEdit_var_4.setText(_translate("edge2d_window", "filename"))
        self.lineEdit_var_5.setText(_translate("edge2d_window", "variable1"))

