# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eqdsk_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_eqdsk_window(object):
    def setupUi(self, eqdsk_window):
        eqdsk_window.setObjectName("eqdsk_window")
        eqdsk_window.resize(701, 424)
        eqdsk_window.setMinimumSize(QtCore.QSize(701, 424))
        eqdsk_window.setMaximumSize(QtCore.QSize(701, 424))
        self.centralwidget = QtWidgets.QWidget(eqdsk_window)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 30, 651, 351))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_eqdskname = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_eqdskname.setGeometry(QtCore.QRect(10, 40, 171, 21))
        self.lineEdit_eqdskname.setObjectName("lineEdit_eqdskname")
        self.select_eqdsk = QtWidgets.QPushButton(self.groupBox_3)
        self.select_eqdsk.setGeometry(QtCore.QRect(190, 40, 21, 21))
        self.select_eqdsk.setObjectName("select_eqdsk")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(230, 20, 131, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_efit = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_efit.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.radioButton_efit.setObjectName("radioButton_efit")
        self.radioButton_other = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_other.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.radioButton_other.setObjectName("radioButton_other")
        self.pushButton_read = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_read.setGeometry(QtCore.QRect(10, 100, 111, 25))
        self.pushButton_read.setObjectName("pushButton_read")
        self.lineEdit_psioffset = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_psioffset.setGeometry(QtCore.QRect(10, 130, 171, 21))
        self.lineEdit_psioffset.setObjectName("lineEdit_psioffset")
        self.pushButton_writematrix = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_writematrix.setGeometry(QtCore.QRect(440, 40, 141, 25))
        self.pushButton_writematrix.setObjectName("pushButton_writematrix")
        self.pushButton_lcmsmap = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_lcmsmap.setGeometry(QtCore.QRect(440, 110, 111, 25))
        self.pushButton_lcmsmap.setObjectName("pushButton_lcmsmap")
        self.pushButton_solmap = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_solmap.setGeometry(QtCore.QRect(440, 170, 111, 25))
        self.pushButton_solmap.setObjectName("pushButton_solmap")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 10, 171, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_openinputfile = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_openinputfile.setGeometry(QtCore.QRect(10, 70, 111, 25))
        self.pushButton_openinputfile.setObjectName("pushButton_openinputfile")
        self.eqdsk_exit = QtWidgets.QPushButton(self.groupBox_3)
        self.eqdsk_exit.setGeometry(QtCore.QRect(480, 320, 101, 21))
        self.eqdsk_exit.setObjectName("eqdsk_exit")
        self.pushButton_lcmsmapX = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_lcmsmapX.setGeometry(QtCore.QRect(440, 140, 111, 25))
        self.pushButton_lcmsmapX.setObjectName("pushButton_lcmsmapX")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 180, 360, 145))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_getmagneticdata = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_getmagneticdata.setObjectName("pushButton_getmagneticdata")
        self.gridLayout.addWidget(self.pushButton_getmagneticdata, 0, 0, 1, 1)
        self.lineEdit_labelIN = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_labelIN.setObjectName("lineEdit_labelIN")
        self.gridLayout.addWidget(self.lineEdit_labelIN, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.pushButton_writemagneticdata = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_writemagneticdata.setObjectName("pushButton_writemagneticdata")
        self.gridLayout.addWidget(self.pushButton_writemagneticdata, 1, 0, 1, 1)
        self.lineEdit_labelOUT = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_labelOUT.setObjectName("lineEdit_labelOUT")
        self.gridLayout.addWidget(self.lineEdit_labelOUT, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.checkBox_normalize = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_normalize.setObjectName("checkBox_normalize")
        self.gridLayout.addWidget(self.checkBox_normalize, 2, 0, 1, 1)
        self.checkBox_invert = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_invert.setObjectName("checkBox_invert")
        self.gridLayout.addWidget(self.checkBox_invert, 3, 0, 1, 1)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.lineEdit_eqdskname.raise_()
        self.select_eqdsk.raise_()
        self.pushButton_read.raise_()
        self.lineEdit_psioffset.raise_()
        self.pushButton_writematrix.raise_()
        self.pushButton_lcmsmap.raise_()
        self.pushButton_solmap.raise_()
        self.eqdsk_exit.raise_()
        self.pushButton_lcmsmapX.raise_()
        self.groupBox_4.raise_()
        eqdsk_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(eqdsk_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 20))
        self.menubar.setObjectName("menubar")
        eqdsk_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(eqdsk_window)
        self.statusbar.setObjectName("statusbar")
        eqdsk_window.setStatusBar(self.statusbar)

        self.retranslateUi(eqdsk_window)
        QtCore.QMetaObject.connectSlotsByName(eqdsk_window)

    def retranslateUi(self, eqdsk_window):
        _translate = QtCore.QCoreApplication.translate
        eqdsk_window.setWindowTitle(_translate("eqdsk_window", "eqdsk tools"))
        self.groupBox_3.setTitle(_translate("eqdsk_window", "EQDSK"))
        self.select_eqdsk.setText(_translate("eqdsk_window", "..."))
        self.groupBox.setTitle(_translate("eqdsk_window", "source"))
        self.radioButton_efit.setText(_translate("eqdsk_window", "eFit"))
        self.radioButton_other.setText(_translate("eqdsk_window", "other"))
        self.pushButton_read.setText(_translate("eqdsk_window", "read"))
        self.lineEdit_psioffset.setText(_translate("eqdsk_window", "7.4032"))
        self.pushButton_writematrix.setText(_translate("eqdsk_window", "write_input_matrix"))
        self.pushButton_lcmsmap.setText(_translate("eqdsk_window", "run LCMSmap"))
        self.pushButton_solmap.setText(_translate("eqdsk_window", "run SOLmap"))
        self.groupBox_2.setTitle(_translate("eqdsk_window", "mapping tools"))
        self.pushButton_openinputfile.setText(_translate("eqdsk_window", "open input file"))
        self.eqdsk_exit.setText(_translate("eqdsk_window", "exit"))
        self.pushButton_lcmsmapX.setText(_translate("eqdsk_window", "run LCMSXmap"))
        self.groupBox_4.setTitle(_translate("eqdsk_window", "magnetic data"))
        self.pushButton_getmagneticdata.setText(_translate("eqdsk_window", "get magnetic data"))
        self.lineEdit_labelIN.setText(_translate("eqdsk_window", "LFE_81472"))
        self.label.setText(_translate("eqdsk_window", "label IN"))
        self.pushButton_writemagneticdata.setText(_translate("eqdsk_window", "write magnetic data"))
        self.lineEdit_labelOUT.setText(_translate("eqdsk_window", "LFEexp_JET_python"))
        self.label_2.setText(_translate("eqdsk_window", "label OUT"))
        self.checkBox_normalize.setText(_translate("eqdsk_window", "normalize"))
        self.checkBox_invert.setText(_translate("eqdsk_window", "invert"))

